[profile.default]
src = "."
out = "out"
libs = ["lib"]

# 排除OpenZeppelin certora目录
exclude = ["lib/openzeppelin-contracts/certora/**"]

# 启用优化器和IR
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Dependencies
[profile.default.dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", version = "1.9.5" }

# Remappings
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
